package gui.menu;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author GIGABYTE
 */
public class Frm_MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frm_MenuPrincipal.class.getName());

    /**
     * Creates new form Frm_MenuPrincipal
     */
    public Frm_MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        btnMesa = new javax.swing.JButton();
        btnPlatoMenu = new javax.swing.JButton();
        btnCategoria = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnCargo = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnProveedorProducto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();
        menuMantenimiento = new javax.swing.JMenu();
        ItemUsuario = new javax.swing.JMenuItem();
        ItemCliente = new javax.swing.JMenuItem();
        ItemProducto = new javax.swing.JMenuItem();
        ItemProveedor = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("MENU PRINCIPAL");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 240, 70));

        panelMenu.setBackground(new java.awt.Color(51, 51, 51));
        panelMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelMenu.setLayout(null);

        btnMesa.setBackground(new java.awt.Color(0, 0, 0));
        btnMesa.setForeground(new java.awt.Color(255, 255, 255));
        btnMesa.setText("Mesa");
        btnMesa.setAlignmentY(20.0F);
        panelMenu.add(btnMesa);
        btnMesa.setBounds(20, 10, 80, 23);

        btnPlatoMenu.setBackground(new java.awt.Color(0, 0, 0));
        btnPlatoMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnPlatoMenu.setText("Plato Menu");
        btnPlatoMenu.setAlignmentY(70.0F);
        panelMenu.add(btnPlatoMenu);
        btnPlatoMenu.setBounds(20, 40, 100, 23);

        btnCategoria.setBackground(new java.awt.Color(0, 0, 0));
        btnCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btnCategoria.setText("Categoria");
        btnCategoria.setAlignmentY(120.0F);
        panelMenu.add(btnCategoria);
        btnCategoria.setBounds(20, 70, 90, 20);

        btnClientes.setBackground(new java.awt.Color(0, 0, 0));
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setText("Clientes ");
        btnClientes.setAlignmentY(170.0F);
        panelMenu.add(btnClientes);
        btnClientes.setBounds(20, 100, 90, 23);

        btnCargo.setBackground(new java.awt.Color(0, 0, 0));
        btnCargo.setForeground(new java.awt.Color(255, 255, 255));
        btnCargo.setText("Cargo");
        btnCargo.setAlignmentY(220.0F);
        panelMenu.add(btnCargo);
        btnCargo.setBounds(20, 130, 72, 23);

        btnUsuario.setBackground(new java.awt.Color(0, 0, 0));
        btnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario.setText("Usuario");
        btnUsuario.setAlignmentY(270.0F);
        btnUsuario.addActionListener(this::btnUsuarioActionPerformed);
        panelMenu.add(btnUsuario);
        btnUsuario.setBounds(20, 160, 72, 23);

        btnProducto.setBackground(new java.awt.Color(0, 0, 0));
        btnProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnProducto.setText("Producto");
        btnProducto.setAlignmentY(320.0F);
        panelMenu.add(btnProducto);
        btnProducto.setBounds(20, 190, 90, 23);

        btnProveedor.setBackground(new java.awt.Color(0, 0, 0));
        btnProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnProveedor.setText("Proveedor");
        btnProveedor.setAlignmentY(370.0F);
        panelMenu.add(btnProveedor);
        btnProveedor.setBounds(20, 220, 90, 23);

        btnProveedorProducto.setBackground(new java.awt.Color(0, 0, 0));
        btnProveedorProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnProveedorProducto.setText("Prov-Producto");
        btnProveedorProducto.setAlignmentY(420.0F);
        btnProveedorProducto.addActionListener(this::btnProveedorProductoActionPerformed);
        panelMenu.add(btnProveedorProducto);
        btnProveedorProducto.setBounds(20, 250, 110, 30);

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 320));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 510));

        menuArchivo.setText("Archivo");

        itemSalir.setText("Salir");
        itemSalir.addActionListener(this::itemSalirActionPerformed);
        menuArchivo.add(itemSalir);

        jMenuBar1.add(menuArchivo);

        menuMantenimiento.setText("Mantenimiento");

        ItemUsuario.setText("Usuario");
        ItemUsuario.addActionListener(this::ItemUsuarioActionPerformed);
        menuMantenimiento.add(ItemUsuario);

        ItemCliente.setText("Cliente");
        ItemCliente.addActionListener(this::ItemClienteActionPerformed);
        menuMantenimiento.add(ItemCliente);

        ItemProducto.setText("Producto");
        menuMantenimiento.add(ItemProducto);

        ItemProveedor.setText("Proveedor");
        menuMantenimiento.add(ItemProveedor);

        jMenuBar1.add(menuMantenimiento);

        menuAyuda.setText("Ayuda");

        itemAcerca.setText("Acerca de");
        itemAcerca.addActionListener(this::itemAcercaActionPerformed);
        menuAyuda.add(itemAcerca);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnProveedorProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProveedorProductoActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_itemSalirActionPerformed

    private void ItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemUsuarioActionPerformed
        //Frm_Usuario frm = new Frm_Usuario();
        //frm.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ItemUsuarioActionPerformed

    private void ItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemClienteActionPerformed

    private void itemAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaActionPerformed
    JOptionPane.showMessageDialog(this, "Bienvenido al sistema");        // TODO add your handling code here:
    }//GEN-LAST:event_itemAcercaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Frm_MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemCliente;
    private javax.swing.JMenuItem ItemProducto;
    private javax.swing.JMenuItem ItemProveedor;
    private javax.swing.JMenuItem ItemUsuario;
    private javax.swing.JButton btnCargo;
    private javax.swing.JButton btnCategoria;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnMesa;
    private javax.swing.JButton btnPlatoMenu;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnProveedorProducto;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JMenuItem itemAcerca;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuMantenimiento;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
